# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.post.voter:
      class: AppBundle\Permissions\PostVoter
      tags:
        - { name: security.voter }

    app.tokens.action_listener:
      class: AppBundle\EventListener\RedirectUserListener
      arguments:
          - "@security.token_storage"
          - "@router"
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

