# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.post.voter:
      class: AppBundle\Permissions\PostVoter
      tags:
        - { name: security.voter }

    repository.post:
      class: AppBundle\Repository\PostRepository
      arguments:
        - "@doctrine.orm.entity_manager"

    repository.comment:
      class: AppBundle\Repository\CommentRepository
      arguments:
        - "@doctrine.orm.entity_manager"

